Add conv_transpose and sigmoid op
jiangjiajun/tvm pull request #13
Opened 2021-08-20 09:55 UTC by wjj19950828

Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

## Do follow Contributes
1、Add Conv2DTranspose and Sigmoid op
2、Add test cases

2021-08-23 13:30 UTC, jiangjiajun requested changes

2021-08-24 12:23 UTC, wjj19950828 commented on tests/python/frontend/paddlepaddle/test_forward.py
> +            self.conv_transpose = nn.Conv2DTranspose(
Done.

2021-08-25 01:57 UTC, jiangjiajun commented on tests/python/frontend/paddlepaddle/test_forward.py
> +    # in tvm for conv transpose operations
TVM不支持groups>1？

2021-08-25 02:53 UTC, wjj19950828 commented on tests/python/frontend/paddlepaddle/test_forward.py
> +    # in tvm for conv transpose operations
对的，在pytorch的单测中也有指出这个

2021-08-25 03:35 UTC, jiangjiajun commented on tests/python/frontend/paddlepaddle/test_forward.py
> +    # in tvm for conv transpose operations
如果groups大于1的时候会怎样

2021-08-25 03:51 UTC, wjj19950828 commented on tests/python/frontend/paddlepaddle/test_forward.py
> +    # in tvm for conv transpose operations
在我将groups设置成3之后跑上述第一个单测会导致维度对不上，如下图
![image](https://user-images.githubusercontent.com/19977378/130723554-823a8c1b-aae0-4ffa-81ac-a4160925fb64.png)

2021-08-30 05:46 UTC, merged